# Generated by Django 3.1.2 on 2021-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0004_auto_20210210_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
